import user1 from '../../assets/images/user1.jpeg'
import user2 from '../../assets/images/user2.jpeg'
import user3 from '../../assets/images/user3.jpeg'
import user4 from '../../assets/images/user4.png'
import user5 from '../../assets/images/user5.png'
import user6 from '../../assets/images/user6.png'
import user7 from '../../assets/images/user7.png'
import user8 from '../../assets/images/user8.png'
import user9 from '../../assets/images/user9.png'
import user10 from '../../assets/images/user10.jpeg'
import user11 from '../../assets/images/user11.jpeg'
import user12 from '../../assets/images/user4.jpeg'

export const UserList = [
    {
        image: user1,
        name: "Jessica",
        description: "Angelic girl next door home alone with a heavenly voice.... hear me moan as you stroke away while confessing your",
        massges: "$0.79",
        call: "$1.19",
        call1: "$1.99",
        call2: "$2.78",
        color: "#20B514",
        liked: true,
    },
    {
        image: user2,
        name: "Mistress Scarlett",
        description: "Serve Me, you worthless pig! Are you ready to be humiliated and abused by Mistress Scarlett?",
        massges: "$0.99",
        call: "$1.48",
        call1: "$2.35",
        call2: "$2.99",
        color: "#EBEBEB",
        liked: false,
    },
    {
        image: user3,
        name: "Maria",
        description: "Hi sweetheart have you had a long day? Perhaps you are bored and just need someone to talk to about all of your",
        massges: "$0.75",
        call: "$1.15",
        call1: "$1.95",
        call2: "$2.45",
        color: "#EBEBEB",
        liked: false,
    },
    {
        image: user4,
        name: "Dom Kate",
        description: "Does your particular fetish involve being taken advantage of by a therapist such as myself? Fantastic! We can play with",
        massges: "$1.09",
        call: "$2.00",
        call1: "$2.85",
        call2: "$3.25",
        color: "#20B514",
        liked: false,
    },
    {
        image: user5,
        name: "Jane Miller",
        description: "I'm a 37 year old milf hornier than any other woman in town. I'm in the prime of my life, DOMINANT and ready to go any",
        massges: "$0.89",
        call: "$1.89",
        call1: "$2.89",
        call2: "$3.89",
        color: "#20B514",
        liked: true,
    },
    {
        image: user6,
        name: "Eric Brown",
        description: "You will be in very safe hands with me, I will take good care of you. My approach is to be supportive, encouraging, and",
        massges: "$0.78",
        call: "$2.03",
        call1: "$2.88",
        call2: "$3.99",
        color: "#20B514",
        liked: false,
    },
    {
        image: user7,
        name: "Elle",
        description: "I'm Elle, a Lifestyle Domme. If you're into forced bi and cross-dressing, you've come to the right place..",
        massges: "$1.00",
        call: "$1.89",
        call1: "$2.39",
        call2: "$2.99",
        color: "#20B514",
        liked: false,
    },
    {
        image: user8,
        name: "Samantha",
        description: "my name is Samantha and I am a super horny 19 Year old girl looking to have some kinky conversation I am open to",
        massges: "$0.87",
        call: "$1.56",
        call1: "$2.06",
        call2: "$5.99",
        color: "#20B514",
        liked: false,
    },
    {
        image: user9,
        name: "Becky",
        description: "I’m Becky! A 19 year old blonde living in Cali. I have a nice round ass and pretty tits and I love to play around. I’m",
        massges: "$1.05",
        call: "$1.75",
        call1: "$1.99",
        call2: "$2.85",
        color: "#20B514",
        liked: true,
    },
    {
        image: user10,
        name: "Loren",
        description: "I'm young sexy and in control. Everything about me is dominating, I have been known to smash guys balls in the concret",
        massges: "$0.97",
        call: "$1.43",
        call1: "$2.10",
        call2: "$2.75",
        color: "#20B514",
        liked: false,
    },
    {
        image: user11,
        name: "Sarah Kim",
        description: "I am looking for sweet, smart, loyal, enthusiastic sluts to get lost with in the land of fuck. Or for friendship. Or all of",
        massges: "$0.75",
        call: "$0.99",
        call1: "$1.45",
        call2: "$2.78",
        color: "#20B514",
        liked: false,
    },
    {
        image: user12,
        name: "Joanna",
        description: "DO YOU LONG TO BE DRESSED AND DRAPED IN FEMININE CLOTHING? WHATEVER FEMINIZING DESIRES YOU",
        massges: "$0.89",
        call: "$1.25",
        call1: "$1.95",
        call2: "$2.35",
        color: "#20B514",
        liked: false,
    },
]